 SELECT
    GA.CODIGOGA,
    TRUNC(KH.DATA_BASE_HOD, 'MM') AS DATA_MES_ANO,
    ROUND(SUM(KH.KM_HOD) - NVL(SUM(KE.KM_ESP), 0) - NVL(SUM(KI.KMTOTALINT), 0), 2) AS KM_HOD2
FROM
    (
        SELECT 
            V.CODIGOGA, 
            TRUNC(C.DATAVELOC, 'MM') AS DATA_BASE_HOD, 
            SUM(C.KMPERCORRIDOVELOC) AS KM_HOD
        FROM 
            VWABA_CONFKMCARRO C
            JOIN FRT_CADVEICULOS V ON V.CODIGOVEIC = C.CODIGOVEIC
            JOIN FRT_TIPODEFROTA F ON V.CODIGOTPFROTA = F.CODIGOTPFROTA
        WHERE 
            C.DATAVELOC >= TO_DATE(:1, 'YYYY-MM-DD')
            AND C.DATAVELOC < TO_DATE(:2, 'YYYY-MM-DD') + 1
            AND TO_TIMESTAMP(TO_CHAR(C.DATAVELOC, 'DD-MON-YYYY') || ' ' || C.HORAVELOC, 'DD-MON-YYYY HH24:MI') >= 
                TO_TIMESTAMP(TO_CHAR(C.DATAVELOC, 'DD-MON-YYYY') || ' 04:00', 'DD-MON-YYYY HH24:MI')
            AND V.CODIGOEMPRESA = 4 
            AND V.CONDICAOVEIC = 'A' 
            AND V.CODIGOGA IN (31, 124, 239, 240)
        GROUP BY 
            V.CODIGOGA, TRUNC(C.DATAVELOC, 'MM')
    ) KH
    LEFT JOIN (
        SELECT 
            V.CODIGOGA, 
            TRUNC(M.DTSAIDA, 'MM') AS DATA_BASE_ESP, 
            SUM(M.ODOMETROFIN - M.ODOMETROINIC) AS KM_ESP
        FROM 
            PLT_SAIDARECOLHIDA M
            JOIN PLT_OCORRENCIAS O ON M.CODOCORRPLTSAIDA = O.CODOCORRPLT
            JOIN FRT_CADVEICULOS V ON M.CODIGOVEIC = V.CODIGOVEIC
            JOIN FRT_TIPODEFROTA F ON V.CODIGOTPFROTA = F.CODIGOTPFROTA
        WHERE 
            M.DTSAIDA >= TO_DATE(:1, 'YYYY-MM-DD') 
            AND M.DTSAIDA < TO_DATE(:2, 'YYYY-MM-DD') + 1
            AND M.CODOCORRPLTSAIDA BETWEEN 17 AND 26 
            AND V.CODIGOEMPRESA = 4 
            AND V.CONDICAOVEIC = 'A' 
            AND V.CODIGOGA IN (31, 124, 239, 240)
        GROUP BY 
            V.CODIGOGA, TRUNC(M.DTSAIDA, 'MM')
    ) KE ON KH.CODIGOGA = KE.CODIGOGA AND KH.DATA_BASE_HOD = KE.DATA_BASE_ESP
    LEFT JOIN (
        SELECT 
            V.CODIGOGA,
            TRUNC(TO_DATE(:1, 'YYYY-MM-DD'), 'MM') AS DATA_BASE_KI,
            SUM(
                CASE 
                    WHEN V.CODIGOGA IN (31, 239) THEN 0.60 
                    WHEN V.CODIGOTPFROTA IN (11, 9) AND V.CODIGOGA = 240 THEN 0.21 
                    WHEN V.CODIGOTPFROTA IN (3, 12) AND V.CODIGOGA = 240 THEN 0.60 
                    WHEN V.CODIGOTPFROTA = 9 AND V.CODIGOGA = 124 THEN 0.60 
                    WHEN V.CODIGOTPFROTA NOT IN (9) AND V.CODIGOGA = 124 THEN 0.80 
                    ELSE 0 
                END
            ) AS KMTOTALINT
        FROM 
            FRT_CADVEICULOS V
            JOIN FRT_TIPODEFROTA F ON V.CODIGOTPFROTA = F.CODIGOTPFROTA
        WHERE 
            V.CODIGOEMPRESA = 4 
            AND LENGTH(TO_NUMBER(V.PREFIXOVEIC)) > 5 
            AND V.CONDICAOVEIC = 'A' 
            AND V.CODIGOGA NOT IN (4) 
            AND V.CODIGOGA IN (31, 124, 239, 240)
        GROUP BY 
            V.CODIGOGA, TRUNC(TO_DATE(:1, 'YYYY-MM-DD'), 'MM')
    ) KI ON KH.CODIGOGA = KI.CODIGOGA AND KH.DATA_BASE_HOD = KI.DATA_BASE_KI
    JOIN (
        SELECT DISTINCT CODIGOGA 
        FROM FRT_CADVEICULOS 
        WHERE CODIGOGA IN (31, 124, 239, 240)
    ) GA ON KH.CODIGOGA = GA.CODIGOGA
WHERE 
    KH.DATA_BASE_HOD IS NOT NULL
GROUP BY 
    GA.CODIGOGA, TRUNC(KH.DATA_BASE_HOD, 'MM')
ORDER BY 
    GA.CODIGOGA, TRUNC(KH.DATA_BASE_HOD, 'MM')